[project]
name = "windowonly"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "imageio-ffmpeg>=0.5.0",
    "pyinstaller>=6.0.0",
    "yt-dlp>=2024.0.0",
]
